namespace Esfa.Vacancy.Register.Domain.Validation
{
    public static class ErrorMessages
    {
        public static class SearchApprenticeships
        {
            public const string SearchApprenticeshipParametersIsNull = "At least one search parameter is required.";

            public const string StandardAndFrameworkCodeNotProvided =  "30101";
            public const string StandardCodeNotInt32 =                 "30102";
            public const string FrameworkCodeNotInt32 =                "30103";
            //public const string PageSizeLessThan1 =                    "this message is auto-generated by fluent validator";
            //public const string PageSizeGreaterThan250 =               "this message is auto-generated by fluent validator";
            //public const string PageNumberLessThan1 =                  "this message is auto-generated by fluent validator";
            //public const string PostedInLastNumberOfDaysLessThan0 =    "this message is auto-generated by fluent validator";

            public const string FrameworkCodeNotFound =                "30108";
            public const string StandardCodeNotFound =                 "30109";
        }

        public static class GetApprenticeship
        {
            //public const string VacancyReferenceNumberLessThan0 =      "this message is auto-generated by fluent validator";
        }

        public static class SearchTraineeships
        {

        }

        public static class GetTraineeship
        {
            //public const string VacancyReferenceNumberLessThan0 =      "this message is auto-generated by fluent validator";
        }
    }
}